[package]
name = "nanondef"
version.workspace = true
authors.workspace = true
edition.workspace = true

[workspace]
members = ["nanondef-sys","nanondef-wasm"]

[workspace.package]
version = "0.1.0"
authors = ["John P. Lettman <the@johnlettman.com>"]
edition = "2021"

[features]
default = ["std", "serde", "tracing"]

std = ["serde?/std", "tracing?/std", "wasm-bindgen?/std"]
alloc = ["serde?/alloc", "heapless/alloc"]

tracing = ["dep:tracing"]
serde = ["dep:serde", "heapless/serde", "wasm-bindgen?/serde", "wasm-bindgen?/serde-serialize"]
wasm = ["dep:wasm-bindgen"]

nightly_doc = []

_ffi_cbindgen = []

[dependencies]
tracing = { version = "0.1", features = ["attributes", "tracing-attributes"], default-features = false, optional = true }
tracing-test = { version = "0.2" }
thiserror = { version = "2.0" }

derive-new = { version = "0.7" }
const_format = "0.2"
pastey = "0.2"

serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
wasm-bindgen = {version = "0.2", default-features = false, optional = true}
heapless = { version = "0.9" }

[dev-dependencies]

